### ISSUE TITLE
Request for References or articles

### ISSUE THREAD

**Issue by f8eddy** [inovex/RCIS2021-degradation-estimation-bearing-vessels#1]
Hello,
I was looking at your project , which it seems interesting and well programmed.
I would like to know if it's possible to share with me any references or articles made or related to this project.
Thanks in advance. Regards.

**Comment by nils-mohr** [comment]
Hey @f8eddy,
Thanks for your message. 
Sure, the project is part of a publication at RCIS 2021 (http://www.rcis-conf.com/rcis2021/). Unfortunately our research paper is not yet published as it still need to be presented at the conference mid May. After the conference you can find our paper with some might insights in the proceedings of the conference.

Hope this helps,
Best Nils

**Comment by f8eddy** [comment]
Ah okay thank you. 
Regards.
